spring.application.name=WatchOut
# Server Configuration
server.port=8080

# Logging for WebSocket Debugging (Highly recommended for development)
# This will show you in the console when a client connects or sends a message
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG

# Enable hot swapping for static files (so you don't have to restart for CSS/JS changes)
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/